# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

if Rails.env.development?
  Timeslot.create(day: "Monday", time: "Breakfast")
  Timeslot.create(day: "Tuesday", time: "Breakfast")
  Timeslot.create(day: "Wednesday", time: "Breakfast")
  Timeslot.create(day: "Thursday", time: "Breakfast")
  Timeslot.create(day: "Friday", time: "Breakfast")
  Timeslot.create(day: "Saturday", time: "Breakfast")
  Timeslot.create(day: "Sunday", time: "Breakfast")
  Timeslot.create(day: "Monday", time: "Lunch")
  Timeslot.create(day: "Tuesday", time: "Lunch")
  Timeslot.create(day: "Wednesday", time: "Lunch")
  Timeslot.create(day: "Thursday", time: "Lunch")
  Timeslot.create(day: "Friday", time: "Lunch")
  Timeslot.create(day: "Saturday", time: "Lunch")
  Timeslot.create(day: "Sunday", time: "Lunch")
  Timeslot.create(day: "Monday", time: "Dinner")
  Timeslot.create(day: "Tuesday", time: "Dinner")
  Timeslot.create(day: "Wednesday", time: "Dinner")
  Timeslot.create(day: "Thursday", time: "Dinner")
  Timeslot.create(day: "Friday", time: "Dinner")
  Timeslot.create(day: "Saturday", time: "Dinner")
  Timeslot.create(day: "Sunday", time: "Dinner")
  Timeslot.create(day: "Monday", time: "Late-night")
  Timeslot.create(day: "Tuesday", time: "Late-night")
  Timeslot.create(day: "Wednesday", time: "Late-night")
  Timeslot.create(day: "Thursday", time: "Late-night")
  Timeslot.create(day: "Friday", time: "Late-night")
  Timeslot.create(day: "Saturday", time: "Late-night")
  Timeslot.create(day: "Sunday", time: "Late-night")

  Location.create(address: "Greenway, Rowes Wharf Plaza")
  Location.create(address: "Clarendon St at Trinity Church")
  Location.create(address: "Financial District, Pearl Street at Franklin")
  Location.create(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain")
  Location.create(address: "Greenway, Dewey Square Park Plaza")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Downtown - City Hall Plaza, Fisher Park")
  Location.create(address: "NEU, on Opera Place at Huntington Ave")
  Location.create(address: "Stuart St. at Trinity Place")
  Location.create(address: "Boston Public Library")
  Location.create(address: "South End - Harrison Ave and East Concord St, by BMC")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")
  Location.create(address: "Innovation District, Seaport Blvd at Boston Wharf Rd")
  Location.create(address: "Greenway - Carousel")
  Location.create(address: "Greenway, Rings Fountain at Milk St")
  Location.create(address: "Greenway, Chinatown Park")
  Location.create(address: "Financial District, Milk and Kilby Streets")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Dudley Square at Dudley street")
  Location.create(address: "Dorchester, Ashmont Station on Dorchester Ave")
  Location.create(address: "Hurley Building, New Chardon and Cambridge St")
  Location.create(address: "Charlestown Navy Yard at Baxter Road")
  Location.create(address: "Greenway, Dewey Square Park at Congress St")
  Location.create(address: "Chinatown, Boylston St near Washington St")
  Location.create(address: "Boston University - West, on Commonwealth Ave, adjacent to 855 Commonwealth Ave")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")

  Truck.create(name: "Baja Taco Truck")
  Truck.create(name: "Big Daddy Hotdogs")
  Truck.create(name: "Blazing Salads")
  Truck.create(name: "Bon Me")
  Truck.create(name: "Boston Burger Company")
  Truck.create(name: "Boston's Baddest Burger & Sandwich Co.")
  Truck.create(name: "Capriotti's")
  Truck.create(name: "Captain Marden's Cod Squad")
  Truck.create(name: "Chicken & Rice Guys")
  Truck.create(name: "Chik Chak")
  Truck.create(name: "Chili Mango & Lime")
  Truck.create(name: "Chubby Chickpea")
  Truck.create(name: "Clover")
  Truck.create(name: "Compliments")
  Truck.create(name: "Cookie Monstah")
  Truck.create(name: "Cupcake City")
  Truck.create(name: "Daddy's Bonetown Burgers")
  Truck.create(name: "Dragon Roll")
  Truck.create(name: "Fresh Food Generation")
  Truck.create(name: "Frozen Hoagies")
  Truck.create(name: "Frozen Hoagies 2")
  Truck.create(name: "Gogi on the Block")
  Truck.create(name: "Heritage Truck Company")
  Truck.create(name: "Indulge India")
  Truck.create(name: "Jamaica Mi Hungry")
  Truck.create(name: "KimKim BBQ")
  Truck.create(name: "Makin' Jamaican")
  Truck.create(name: "Mediterranean Home Cooking")
  Truck.create(name: "Mei Mei Street Kitchen")
  Truck.create(name: "Meng's Kitchen")
  Truck.create(name: "Mo' Rockin Fusion")
  Truck.create(name: "Momogoose")
  Truck.create(name: "Morning Salute")
  Truck.create(name: "Moyzilla")
  Truck.create(name: "Munch Mobile")
  Truck.create(name: "Northeast of the Border")
  Truck.create(name: "Papi's Stuffed Sopapillias")
  Truck.create(name: "Pennypackers")
  Truck.create(name: "Posto Mobile")
  Truck.create(name: "Quebrada Baking Co")
  Truck.create(name: "Redbones Barbeque")
  Truck.create(name: "Riceburg")
  Truck.create(name: "Roxy's Gourmet Grilled Cheese")
  Truck.create(name: "Sabroso Taqueria")
  Truck.create(name: "Saigon Alley")
  Truck.create(name: "Savory Food Truck 1")
  Truck.create(name: "Savory Food Truck 2")
  Truck.create(name: "Sheherazad")
  Truck.create(name: "Slide By Food Truck")
  Truck.create(name: "Spiceventure")
  Truck.create(name: "Stoked Wood Fired Pizza Co.")
  Truck.create(name: "Sweet Bubble")
  Truck.create(name: "Sweet Tomatoes Pizza")
  Truck.create(name: "Taco Party")
  Truck.create(name: "Tea Station")
  Truck.create(name: "Tenoch Mexican")
  Truck.create(name: "Teri-Yummy")
  Truck.create(name: "Teri-Yummy 2")
  Truck.create(name: "The Bacon Truck")
  Truck.create(name: "The Dining Car")
  Truck.create(name: "The Roving Lunchbox")
  Truck.create(name: "Trolley Dogs")
  Truck.create(name: "Walloon's")
  Truck.create(name: "Yumm Bai")
  Truck.create(name: "Zinneken's Waffles")
  Truck.create(name: "Zo on the Go")
end

if Rails.env.production?
  Timeslot.create(day: "Monday", time: "Breakfast")
  Timeslot.create(day: "Tuesday", time: "Breakfast")
  Timeslot.create(day: "Wednesday", time: "Breakfast")
  Timeslot.create(day: "Thursday", time: "Breakfast")
  Timeslot.create(day: "Friday", time: "Breakfast")
  Timeslot.create(day: "Saturday", time: "Breakfast")
  Timeslot.create(day: "Sunday", time: "Breakfast")
  Timeslot.create(day: "Monday", time: "Lunch")
  Timeslot.create(day: "Tuesday", time: "Lunch")
  Timeslot.create(day: "Wednesday", time: "Lunch")
  Timeslot.create(day: "Thursday", time: "Lunch")
  Timeslot.create(day: "Friday", time: "Lunch")
  Timeslot.create(day: "Saturday", time: "Lunch")
  Timeslot.create(day: "Sunday", time: "Lunch")
  Timeslot.create(day: "Monday", time: "Dinner")
  Timeslot.create(day: "Tuesday", time: "Dinner")
  Timeslot.create(day: "Wednesday", time: "Dinner")
  Timeslot.create(day: "Thursday", time: "Dinner")
  Timeslot.create(day: "Friday", time: "Dinner")
  Timeslot.create(day: "Saturday", time: "Dinner")
  Timeslot.create(day: "Sunday", time: "Dinner")
  Timeslot.create(day: "Monday", time: "Late-night")
  Timeslot.create(day: "Tuesday", time: "Late-night")
  Timeslot.create(day: "Wednesday", time: "Late-night")
  Timeslot.create(day: "Thursday", time: "Late-night")
  Timeslot.create(day: "Friday", time: "Late-night")
  Timeslot.create(day: "Saturday", time: "Late-night")
  Timeslot.create(day: "Sunday", time: "Late-night")

  Location.create(address: "Greenway, Rowes Wharf Plaza")
  Location.create(address: "Clarendon St at Trinity Church")
  Location.create(address: "Financial District, Pearl Street at Franklin")
  Location.create(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain")
  Location.create(address: "Greenway, Dewey Square Park Plaza")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Downtown - City Hall Plaza, Fisher Park")
  Location.create(address: "NEU, on Opera Place at Huntington Ave")
  Location.create(address: "Stuart St. at Trinity Place")
  Location.create(address: "Boston Public Library")
  Location.create(address: "South End - Harrison Ave and East Concord St, by BMC")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")
  Location.create(address: "Innovation District, Seaport Blvd at Boston Wharf Rd")
  Location.create(address: "Greenway - Carousel")
  Location.create(address: "Greenway, Rings Fountain at Milk St")
  Location.create(address: "Greenway, Chinatown Park")
  Location.create(address: "Financial District, Milk and Kilby Streets")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Dudley Square at Dudley street")
  Location.create(address: "Dorchester, Ashmont Station on Dorchester Ave")
  Location.create(address: "Hurley Building, New Chardon and Cambridge St")
  Location.create(address: "Charlestown Navy Yard at Baxter Road")
  Location.create(address: "Greenway, Dewey Square Park at Congress St")
  Location.create(address: "Chinatown, Boylston St near Washington St")
  Location.create(address: "Boston University - West, on Commonwealth Ave, adjacent to 855 Commonwealth Ave")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")

  Truck.create(name: "Baja Taco Truck")
  Truck.create(name: "Big Daddy Hotdogs")
  Truck.create(name: "Blazing Salads")
  Truck.create(name: "Bon Me")
  Truck.create(name: "Boston Burger Company")
  Truck.create(name: "Boston's Baddest Burger & Sandwich Co.")
  Truck.create(name: "Capriotti's")
  Truck.create(name: "Captain Marden's Cod Squad")
  Truck.create(name: "Chicken & Rice Guys")
  Truck.create(name: "Chik Chak")
  Truck.create(name: "Chili Mango & Lime")
  Truck.create(name: "Chubby Chickpea")
  Truck.create(name: "Clover")
  Truck.create(name: "Compliments")
  Truck.create(name: "Cookie Monstah")
  Truck.create(name: "Cupcake City")
  Truck.create(name: "Daddy's Bonetown Burgers")
  Truck.create(name: "Dragon Roll")
  Truck.create(name: "Fresh Food Generation")
  Truck.create(name: "Frozen Hoagies")
  Truck.create(name: "Frozen Hoagies 2")
  Truck.create(name: "Gogi on the Block")
  Truck.create(name: "Heritage Truck Company")
  Truck.create(name: "Indulge India")
  Truck.create(name: "Jamaica Mi Hungry")
  Truck.create(name: "KimKim BBQ")
  Truck.create(name: "Makin' Jamaican")
  Truck.create(name: "Mediterranean Home Cooking")
  Truck.create(name: "Mei Mei Street Kitchen")
  Truck.create(name: "Meng's Kitchen")
  Truck.create(name: "Mo' Rockin Fusion")
  Truck.create(name: "Momogoose")
  Truck.create(name: "Morning Salute")
  Truck.create(name: "Moyzilla")
  Truck.create(name: "Munch Mobile")
  Truck.create(name: "Northeast of the Border")
  Truck.create(name: "Papi's Stuffed Sopapillias")
  Truck.create(name: "Pennypackers")
  Truck.create(name: "Posto Mobile")
  Truck.create(name: "Quebrada Baking Co")
  Truck.create(name: "Redbones Barbeque")
  Truck.create(name: "Riceburg")
  Truck.create(name: "Roxy's Gourmet Grilled Cheese")
  Truck.create(name: "Sabroso Taqueria")
  Truck.create(name: "Saigon Alley")
  Truck.create(name: "Savory Food Truck 1")
  Truck.create(name: "Savory Food Truck 2")
  Truck.create(name: "Sheherazad")
  Truck.create(name: "Slide By Food Truck")
  Truck.create(name: "Spiceventure")
  Truck.create(name: "Stoked Wood Fired Pizza Co.")
  Truck.create(name: "Sweet Bubble")
  Truck.create(name: "Sweet Tomatoes Pizza")
  Truck.create(name: "Taco Party")
  Truck.create(name: "Tea Station")
  Truck.create(name: "Tenoch Mexican")
  Truck.create(name: "Teri-Yummy")
  Truck.create(name: "Teri-Yummy 2")
  Truck.create(name: "The Bacon Truck")
  Truck.create(name: "The Dining Car")
  Truck.create(name: "The Roving Lunchbox")
  Truck.create(name: "Trolley Dogs")
  Truck.create(name: "Walloon's")
  Truck.create(name: "Yumm Bai")
  Truck.create(name: "Zinneken's Waffles")
  Truck.create(name: "Zo on the Go")
end
