# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars' }, { name: "Lord of the Rings' }])
#   Character.create(name: "Luke', movie: movies.first)

if (Rails.env.development? || Rails.env.production? || Rails.env.test?)
  Appointment.destroy_all
  Timeslot.destroy_all
  Location.destroy_all
  Truck.destroy_all

  Timeslot.create(day: "Monday", time: "Breakfast")
  Timeslot.create(day: "Monday", time: "Lunch")
  Timeslot.create(day: "Monday", time: "Dinner")
  Timeslot.create(day: "Monday", time: "Late-night")
  Timeslot.create(day: "Tuesday", time: "Breakfast")
  Timeslot.create(day: "Tuesday", time: "Lunch")
  Timeslot.create(day: "Tuesday", time: "Dinner")
  Timeslot.create(day: "Tuesday", time: "Late-night")
  Timeslot.create(day: "Wednesday", time: "Breakfast")
  Timeslot.create(day: "Wednesday", time: "Lunch")
  Timeslot.create(day: "Wednesday", time: "Dinner")
  Timeslot.create(day: "Wednesday", time: "Late-night")
  Timeslot.create(day: "Thursday", time: "Breakfast")
  Timeslot.create(day: "Thursday", time: "Lunch")
  Timeslot.create(day: "Thursday", time: "Dinner")
  Timeslot.create(day: "Thursday", time: "Late-night")
  Timeslot.create(day: "Friday", time: "Breakfast")
  Timeslot.create(day: "Friday", time: "Lunch")
  Timeslot.create(day: "Friday", time: "Dinner")
  Timeslot.create(day: "Friday", time: "Late-night")
  Timeslot.create(day: "Saturday", time: "Breakfast")
  Timeslot.create(day: "Saturday", time: "Lunch")
  Timeslot.create(day: "Saturday", time: "Dinner")
  Timeslot.create(day: "Saturday", time: "Late-night")
  Timeslot.create(day: "Sunday", time: "Breakfast")
  Timeslot.create(day: "Sunday", time: "Lunch")
  Timeslot.create(day: "Sunday", time: "Dinner")
  Timeslot.create(day: "Sunday", time: "Late-night")

  Location.create(address: "Greenway, Rowes Wharf Plaza")
  Location.create(address: "Clarendon St at Trinity Church")
  Location.create(address: "Financial District, Pearl Street at Franklin")
  Location.create(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain")
  Location.create(address: "Greenway, Dewey Square Park Plaza")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Downtown - City Hall Plaza, Fisher Park")
  Location.create(address: "NEU, on Opera Place at Huntington Ave")
  Location.create(address: "Stuart St. at Trinity Place")
  Location.create(address: "Boston Public Library")
  Location.create(address: "South End - Harrison Ave and East Concord St, by BMC")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")
  Location.create(address: "Innovation District, Seaport Blvd at Boston Wharf Rd")
  Location.create(address: "Greenway - Carousel")
  Location.create(address: "Greenway, Rings Fountain at Milk St")
  Location.create(address: "Greenway, Chinatown Park")
  Location.create(address: "Financial District, Milk and Kilby Streets")
  Location.create(address: "West End, Blossom St at Emerson Place, behind MGH")
  Location.create(address: "Dudley Square at Dudley street")
  Location.create(address: "Dorchester, Ashmont Station on Dorchester Ave")
  Location.create(address: "Hurley Building, New Chardon and Cambridge St")
  Location.create(address: "Charlestown Navy Yard at Baxter Road")
  Location.create(address: "Greenway, Dewey Square Park at Congress St")
  Location.create(address: "Chinatown, Boylston St near Washington St")
  Location.create(address: "Boston University - West, on Commonwealth Ave, adjacent to 855 Commonwealth Ave")
  Location.create(address: "Boston University - East, on Commonwealth Ave at Silber Way")

  Truck.create(name: "Baja Taco Truck")
  Truck.create(name: "Big Daddy Hotdogs")
  Truck.create(name: "Blazing Salads")
  Truck.create(name: "Bon Me")
  Truck.create(name: "Boston Burger Company")
  Truck.create(name: "Boston's Baddest Burger & Sandwich Co.")
  Truck.create(name: "Capriotti's")
  Truck.create(name: "Captain Marden's Cod Squad")
  Truck.create(name: "Chicken & Rice Guys")
  Truck.create(name: "Chik Chak")
  Truck.create(name: "Chili Mango & Lime")
  Truck.create(name: "Chubby Chickpea")
  Truck.create(name: "Clover")
  Truck.create(name: "Compliments")
  Truck.create(name: "Cookie Monstah")
  Truck.create(name: "Cupcake City")
  Truck.create(name: "Daddy's Bonetown Burgers")
  Truck.create(name: "Dragon Roll")
  Truck.create(name: "Fresh Food Generation")
  Truck.create(name: "Frozen Hoagies")
  Truck.create(name: "Frozen Hoagies 2")
  Truck.create(name: "Gogi on the Block")
  Truck.create(name: "Heritage Truck Company")
  Truck.create(name: "Indulge India")
  Truck.create(name: "Jamaica Mi Hungry")
  Truck.create(name: "KimKim BBQ")
  Truck.create(name: "Makin' Jamaican")
  Truck.create(name: "Mediterranean Home Cooking")
  Truck.create(name: "Mei Mei Street Kitchen")
  Truck.create(name: "Meng's Kitchen")
  Truck.create(name: "Mo' Rockin Fusion")
  Truck.create(name: "Momogoose")
  Truck.create(name: "Morning Salute")
  Truck.create(name: "Moyzilla")
  Truck.create(name: "Munch Mobile")
  Truck.create(name: "Northeast of the Border")
  Truck.create(name: "Papi's Stuffed Sopapillias")
  Truck.create(name: "Pennypackers")
  Truck.create(name: "Posto Mobile")
  Truck.create(name: "Quebrada Baking Co")
  Truck.create(name: "Redbones Barbeque")
  Truck.create(name: "Riceburg")
  Truck.create(name: "Roxy's Gourmet Grilled Cheese")
  Truck.create(name: "Sabroso Taqueria")
  Truck.create(name: "Saigon Alley")
  Truck.create(name: "Savory Food Truck 1")
  Truck.create(name: "Savory Food Truck 2")
  Truck.create(name: "Sheherazad")
  Truck.create(name: "Slide By Food Truck")
  Truck.create(name: "Spiceventure")
  Truck.create(name: "Stoked Wood Fired Pizza Co.")
  Truck.create(name: "Sweet Bubble")
  Truck.create(name: "Sweet Tomatoes Pizza")
  Truck.create(name: "Taco Party")
  Truck.create(name: "Tea Station")
  Truck.create(name: "Tenoch Mexican")
  Truck.create(name: "Teri-Yummy")
  Truck.create(name: "Teri-Yummy 2")
  Truck.create(name: "The Bacon Truck")
  Truck.create(name: "The Dining Car")
  Truck.create(name: "The Roving Lunchbox")
  Truck.create(name: "Trolley Dogs")
  Truck.create(name: "Walloon's")
  Truck.create(name: "Yumm Bai")
  Truck.create(name: "Zinneken's Waffles")
  Truck.create(name: "Zo on the Go")


  Appointment.create(truck: Truck.find_or_create_by(name: "Baja Taco Truck"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Baja Taco Truck"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Baja Taco Truck"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Baja Taco Truck"), location: Location.find_or_create_by(address: "Financial District, Pearl Street at Franklin"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Baja Taco Truck"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "BigDaddy Hotdogs"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Blazing Salads"), location: Location.find_or_create_by(address: "Financial District, Pearl Street at Franklin"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Blazing Salads"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Bon Me"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Boston Burger Company"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Boston's Baddest Burger & Sandwich Co."), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Capriotti's"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Capriotti's"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Captain Marden's Cod Squad"), location: Location.find_or_create_by(address: "Innovation District, Seaport Blvd at Boston Wharf Rd"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Captain Marden's Cod Squad"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Innovation District, Seaport Blvd at Boston Wharf Rd"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Greenway, Chinatown Park"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chicken & Rice Guys"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chik Chak"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chik Chak"), location: Location.find_or_create_by(address: "Greenway, Chinatown Park"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chik Chak"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chik Chak"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chili Mango & Lime"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chili Mango & Lime"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chubby Chickpea"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chubby Chickpea"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chubby Chickpea"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Chubby Chickpea"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Clover"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Compliments"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Compliments"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Sunday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Financial District, Pearl Street at Franklin"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cookie Monstah"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cupcake City"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cupcake City"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Cupcake City"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Daddy's Bonetown Burgers"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Daddy's Bonetown Burgers"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Dragon Roll"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Dragon Roll"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Dragon Roll"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Dragon Roll"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Dragon Roll"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Fresh Food Generation"), location: Location.find_or_create_by(address: "Dudley Square at Dudley street"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Fresh Food Generation"), location: Location.find_or_create_by(address: "Dorchester, Ashmont Station on Dorchester Ave"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Frozen Hoagies 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Gogi on the Block"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Gogi on the Block"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Heritage Truck Company"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Heritage Truck Company"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Indulge India"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Indulge India"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Jamaica Mi Hungry"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Jamaica Mi Hungry"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Jamaica Mi Hungry"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "KimKim BBQ"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "KimKim BBQ"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "KimKim BBQ"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "KimKim BBQ"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "KimKim BBQ"), location: Location.find_or_create_by(address: "Hurley Building, New Chardon and Cambridge St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Makin' Jamaican"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Makin' Jamaican"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mediterranean Home Cooking"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mediterranean Home Cooking"), location: Location.find_or_create_by(address: "Charlestown Navy Yard at Baxter Road"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mediterranean Home Cooking"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mediterranean Home Cooking"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mei Mei Street Kitchen"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mei Mei Street Kitchen"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mei Mei Street Kitchen"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mei Mei Street Kitchen"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Meng's Kitchen"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mo' Rockin Fusion"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mo' Rockin Fusion"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Mo' Rockin Fusion"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Sunday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Momogoose"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Morning Salute"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Morning Salute"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Morning Salute"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Moyzilla"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Munch Mobile"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Munch Mobile"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Northeast of the Border"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Papi's Stuffed Sopapillias"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Pennypackers"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Pennypackers"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Pennypackers"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Pennypackers"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Posto Mobile"), location: Location.find_or_create_by(address: "Innovation District, Seaport Blvd at Boston Wharf Rd"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Posto Mobile"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Posto Mobile"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Quebrada Baking Co."), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Quebrada Baking Co."), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Quebrada Baking Co."), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Quebrada Baking Co."), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Quebrada Baking Co."), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Breakfast"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Redbones Barbeque"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Redbones Barbeque"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Riceburg"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Riceburg"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Riceburg"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Riceburg"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Roxy's Gourmet Grilled Cheese"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sabroso Taqueria"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sabroso Taqueria"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sabroso Taqueria"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sabroso Taqueria"), location: Location.find_or_create_by(address: "Innovation District, Seaport Blvd at Boston Wharf Rd"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Saigon Alley"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Saigon Alley"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Saigon Alley"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 1"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "Boston University - West, on Commonwealth Ave, adjacent to 855 Commonwealth Ave"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Savory Food Truck 2"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sheherazad"), location: Location.find_or_create_by(address: "Financial District, Pearl Street at Franklin"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sheherazad"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sheherazad"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sheherazad"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Slide By Food Truck"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Slide By Food Truck"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Slide By Food Truck"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Spiceventure"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Stoked Wood Fired Pizza Co."), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Stoked Wood Fired Pizza Co."), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Stoked Wood Fired Pizza Co."), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Bubble"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Bubble"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Sunday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Bubble"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Bubble"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Tomatoes Pizza"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Sweet Tomatoes Pizza"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Taco Party"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Taco Party"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Taco Party"), location: Location.find_or_create_by(address: "Financial District, Pearl Street at Franklin"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tea Station"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tea Station"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tea Station"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tea Station"), location: Location.find_or_create_by(address: "Boston Public Library"), timeslot: Timeslot.find_or_create_by(day: "Saturday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Back Bay - Prudential, in front of Christian Science Center's Children's Fountain"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Tenoch Mexican"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Sunday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Sunday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "Dudley Square at Dudley street"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy"), location: Location.find_or_create_by(address: "Chinatown, Boylston St near Washington St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Teri-Yummy 2"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Bacon Truck"), location: Location.find_or_create_by(address: "Innovation District, Seaport Blvd at Boston Wharf Rd"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Bacon Truck"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Dining Car"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Dining Car"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Dining Car"), location: Location.find_or_create_by(address: "Clarendon St at Trinity Church"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Dining Car"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Dining Car"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Roving Lunchbox"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Roving Lunchbox"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "The Roving Lunchbox"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park at Congress St"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Trolley Dogs"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Trolley Dogs"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Greenway, Chinatown Park"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Hurley Building, New Chardon and Cambridge St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Greenway, Rings Fountain at Milk St"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Greenway, Chinatown Park"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "South End - Harrison Ave and East Concord St, by BMC"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Greenway - Carousel"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Walloon's"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Yumm Bai"), location: Location.find_or_create_by(address: "Financial District, Milk and Kilby Streets"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Yumm Bai"), location: Location.find_or_create_by(address: "Downtown - City Hall Plaza, Fisher Park"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "Boston University - East, on Commonwealth Ave at Silber Way"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "Greenway, Chinatown Park"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zinneken's Waffles"), location: Location.find_or_create_by(address: "NEU, on Opera Place at Huntington Ave"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Dinner"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zo on the Go"), location: Location.find_or_create_by(address: "Back Bay - Stuart St. at Trinity Place"), timeslot: Timeslot.find_or_create_by(day: "Friday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zo on the Go"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Monday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zo on the Go"), location: Location.find_or_create_by(address: "Greenway, Rowes Wharf Plaza"), timeslot: Timeslot.find_or_create_by(day: "Thursday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zo on the Go"), location: Location.find_or_create_by(address: "West End, Blossom St at Emerson Place, behind MGH"), timeslot: Timeslot.find_or_create_by(day: "Tuesday", time: "Lunch"))
  Appointment.create(truck: Truck.find_or_create_by(name: "Zo on the Go"), location: Location.find_or_create_by(address: "Greenway, Dewey Square Park Plaza"), timeslot: Timeslot.find_or_create_by(day: "Wednesday", time: "Lunch"))
end
